ecommerceproject/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include


from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('shope/',include('shope.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views


app_name='search_app'
urlpatterns=[
    path('',views.searchresult,name='searchresult')
]

ecommerceproject/shope/urls.py
from django.urls import path
from . import views
app_name='shope'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='proDetail'),
]

ecommerceproject/cart/models.py
from django.db import models

from shope.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return self.cart_id



class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)


    class Meta:
        db_table='CartItem'



    def sub_total(self):
        return self.product.price * self.quantity


    def __str__(self):
        return self.product

ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerceproject/shope/models.py
from django.db import models
from django.urls import reverse



# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'


    def get_url(self):
        return reverse('shope:products_by_category',args=[self.slug])

    def __str__(self):
        return'{}'.format(self.name)





class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('shope:proDetail',args=[self.category.slug,self.slug])

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect
from shope.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

ecommerceproject/search_app/views.py
from django.shortcuts import render
from shope.models import Product
from django.db.models import Q


def searchresult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query= request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecommerceproject/shope/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from shope.models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# def index(request):
#     return HttpResponse('hai')



def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,"category.html",{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
      product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">-->
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
   <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="">

{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}
{% endblock %}
    </div>
{% include 'footer.html' %}
<!--<script src="{% static 'js/popper.min.js' %}"></script>-->
<!--<script src="{% static 'js/bootstrap.min.js' %}"></script>-->
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadiscription %}
Your cart page
{% endblock %}

{% block title %}
    Shope Cart
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Cart is empty
        </h1>
        <br>
        <p class="text-center">
            Click <a href="{% url 'shope:allProdCart' %}">Here</a> & enjoy ur shopeing

        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Cart
        </h1>
        <br>


    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
                <thead class="custom_thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
                </thead>
            <tbody>
            {%  for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"> <img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    Id: {{cart_item_product.id}}
                    <br>
                    Price: ₹{{cart_item.product.price}}
                    <br>
                    Qty: {{cart_item.quantity}} x ₹ {{cart_item.product.price}}
                </td>
                <td>
                    ₹ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}"class="custom_a"> <i class="fa fa-plus-circle custom_icon"></i></a>
                    &nbsp;<a href="" class="custom_a"><i class="fa fa-minus-circle custom_icon"></i> </a>
                    &nbsp;<a href="" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="" class="custom_a"><i class="fa fa-minus-circle custom_icon"></i> </a>
                    &nbsp;<a href="" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                </td>
            </tr>
            {% endfor %}
            </tbody>

        </table>

    </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="my_custom_table">
            <thead>
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
        <tr>
            <td>
                    Rate ur shopping experience
            </td>
        </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shope:allProdCat' %}" class="btn btn-secondary btn0block my-custom-btn">Continue Shopping</a>
        </div>
    </div>

</div>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadiscription %}
      {% if category %}
            {{ category.description|truncatewords:155 }}
      {% else %}
            Welcome to Shope.....
      {% endif %}
{% endblock %}


{% block title %}
      {% if category %}
            {{ category.name}} - Shope
      {% else %}
            See Our New Collections -- Shope
      {% endif %}
{% endblock %}


{% block content %}
{% if category %}

      <div>
            <div class="row my_row_class">
                  <div class="mx-auto">
                   <p><a href="{% url 'shope:allProdCat' %}">Our product Collections</a></p>
             </div>
                  </div>
      </div>
      {% endif %}

<div class="mx-auto">
          {% if category %}
      <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div>
      <br>
<div>
      <h1 class="text_center my_title">{{category.name}}</h1>
      <p class="text_justify">{{category.description}}</p>
</div>
      {% else %}
<div>
      <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products">
</div>
<br>
<div class="container-fluid">
      <h1 class="text-center">Our Product Collections</h1>
      <p  class="text-justify">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary,</p>
</div>
      {% endif %}

<div class="container" style="margin-bottom:60px;">
      <div class="row mx_auto">
           {% for product in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4" >
                  <div class="card text_center" style="minimum_width:18rem;">
                        <a href="{{product.get_url}}"><img class="card_img_top my_image" src="{{product.image.url}}" alt="{{product.name}}"   ></a>
                        <div class="card-body">
                              <h4>{{product.name}}</h4>
                              <p>₹{{product.price}}</p>
                        </div>
                  </div>
            </div>

            {% endfor %}

      </div>
      <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
             <br>
            <div class="text-center">
                  {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>

                  {% endfor %}
            </div>
      {% endif %}
      </div>
      <br>
</div>


{% endblock %}

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">Shope © 2022 All rights Reserved </p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{%url 'shope:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logoimg" height="180px" width="280px"></a>
  </center>

</header>

ecommerceproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">HOME</a>
      <li class="nav-item dropdown {% if 'shope' in request.path %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          SHOPE
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shope:allProdCat' %}">All Products</a>
              {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
              {% endfor %}
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"><i class="fa fa-shopping-bag" ></i></a>
      </li>
    </ul>
      </div>
    <form class="d-flex" action="{% url 'search_app:searchresult' %}" method="get">
      {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
             <button class="btn btn-outline-primary my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>

    </form>



</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is the cart page.proceed to review your items and place the order
{% endblock %}
{% block title %}
  cart - ABC Company pvt LTD

{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart is empty
        </h1>
        <br>
        <p class="text-center">Please Click <a href="{% url 'shop:allProdCat' %}">Here</a>to Continue Shopping</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Sopping Cart</h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
              <th colspan="5">
                  Your items
              </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" style="width:100px; height:100px;" alt="" class="float-left rounded custom_image" ></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU : {{cart_item.product.id}}
                    <br>
                    Price : $ {{cart_item.product.price}}
                    <br>
                    Qty : {{cart_item.quantity}} x $ {{cart_item}}
                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"></i> </a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa fa-minus custom_icon"></i> </a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"> <i class="fa fa-trash custom_icon"></i> </a>
                </td>
                {% else %}
                <td>
                     &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa fa-minus custom_icon"></i> </a>
                     &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"> <i class="fa fa-trash custom_icon"></i> </a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <table class="table my_custom_table">
            <thead class="mu_custom_thead">
            <tr>
                <th>Checkout</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shopping cart items before proceeding with order payment
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your Total is : <strong> {{ total }} </strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary  my_custom_button">Continue shopping</a> <a href="{% url 'shop:allProdCat' %}" class="btn btn-success  my_custom_button"> Make Payment</a>
        </div>
    </div>
</div>

{% endif %}
{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadiscription %}

            We have variety of collections

{% endblock %}

{% block title %}
    Search
{% endblock %}

{% block content %}
    <div>
        <p class="text-center my_search_text">U have searched for:<b>"{{query}}"</b></p>
    </div>
<div class="container" style="margin-bottom:60px;">
      <div class="row mx_auto">
           {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4" >
                  <div class="card text_center" style="minimum_width:18rem;">
                        <a href="{{product.get_url}}"><img class="card_img_top my_image" src="{{product.image.url}}" alt="{{product.name}}"   ></a>
                        <div class="card-body">
                              <h4>{{product.name}}</h4>
                              <p>₹{{product.price}}</p>
                        </div>
                  </div>
            </div>
          {% empty %}
          <div class="row mx-auto">
              <p class="text-center mx-auto"> 0 results</p>
          </div>
          {% endfor %}
      </div>
</div>
<br>
<br>
<br>
{% endblock %}